language: cpp
dist: bionic
sudo: required

# Run Travis CI only on the master branch
branches:
  only:
  - master

matrix:
  include:
    # g++-9 and gcc-9
    - env: CXX=g++-9 CC=gcc-9
      addons:
        apt:
          update: true
          packages:
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
    # g++-10 and gcc-10
    - env: CXX=g++10 CC=gcc-10
      addons:
        apt:
          update: true
          packages:
            - g++-10
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
    # clang++-10 and clang-10
    - env: CXX=clang++-10 CC=clang-10
      addons:
        apt:
          update: true
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    # clang++-11 and clang-11
    - env: CXX=clang++-11 CC=clang-11
      addons:
        apt:
          update: true
          packages:
            - clang-11
            - libc++-11-dev
            - libc++abi-11-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

before_install:
  - sudo apt update
  - sudo apt install qt5-default
  # Manually install newer version of CMake
  - mkdir -p cmake
  - travis_retry wget "https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.tar.gz"
  - tar xf cmake-3.14.5-Linux-x86_64.tar.gz -C cmake --strip-components=1
  - export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  
install: 
  # Check versions of C++ compilers and CMake
  - echo ${CXX}
  - echo ${CC}
  - ${CXX} --version
  - ${CC} --version
  - cmake --version
  # Obtain OpenCV 3.4.2 from source
  - wget https://github.com/opencv/opencv/archive/3.4.2.zip -O opencv-3.4.2.zip
  - unzip opencv-3.4.2.zip && rm opencv-3.4.2.zip
  - cd opencv-3.4.2 && mkdir build && cd build
  # Build OpenCV
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j $(nproc)
  - sudo make install
  - cd ../../

script:
  - mkdir -p build && cd build
  - cmake ..
  - make all
  - make test
